"use client";
import {useState} from "react";
const products=[{name:"LKPD Informatika Kelas X",keyword:"LKPD",file:"LKPD-Informatika-X.pdf",url:"https://example.com/lkpd.pdf"},{name:"My First English",keyword:"INGGRIS",file:"My-First-English.pdf",url:"https://example.com/english.pdf"}];
export default function Home(){
 const [tab,setTab]=useState("Dashboard"),[demo,setDemo]=useState(""),[result,setResult]=useState(null);
 const [campaigns,setCampaigns]=useState([{id:1,name:"LKPD Gratis",keyword:"LKPD",product:"LKPD Informatika Kelas X",platforms:["Instagram","Facebook"],active:true}]);
 const nav=["Dashboard","Campaigns","Products","Instagram","Facebook","Activity","Analytics","Settings"];
 function simulate(){const c=campaigns.find(x=>x.active&&demo.toUpperCase().includes(x.keyword));const p=c&&products.find(x=>x.name===c.product);setResult(c?{ok:true,text:`Keyword "${c.keyword}" cocok dengan campaign "${c.name}".`,c,p}:{ok:false,text:"Tidak ada campaign yang cocok."})}
 return <main><aside className="sidebar"><div className="brand"><div className="logo">H</div><div><b>Hamisah</b><small>Social Auto Reply</small></div></div><nav>{nav.map(n=><button className={tab===n?"active":""} onClick={()=>setTab(n)} key={n}>{n}</button>)}</nav><div className="note">Otomatisasi Instagram & Facebook dibuat sederhana.</div></aside><section className="content"><header><div><span>HAMISAH SOCIAL AUTO REPLY</span><h1>{tab}</h1></div><div className="status">● Instagram &nbsp; ● Facebook</div></header>
 {tab==="Dashboard"&&<><div className="cards">{[["Total Comments","1,248"],["Keyword Matched","386"],["DM Sent","372"],["Messenger Sent","181"],["Active Campaigns",campaigns.filter(x=>x.active).length],["Products",products.length]].map(x=><div className="stat"><small>{x[0]}</small><strong>{x[1]}</strong></div>)}</div><div className="cols"><section className="panel"><h2>Alur otomatis</h2>{["Orang berkomentar: MAU","Webhook menerima komentar","Keyword dicocokkan","Private Reply / Messenger dikirim","Link PDF diterima"].map((x,i)=><div className="flow"><i>0{i+1}</i>{x}</div>)}</section><section className="panel"><div className="panelhead"><div><h2>Demo Mode</h2><p>Simulasikan tanpa Meta.</p></div><em>DEMO MODE</em></div><input value={demo} onChange={e=>setDemo(e.target.value)} placeholder="Contoh: MAU"/><button className="primary" onClick={simulate}>Simulate Comment</button>{result&&<div className={result.ok?"success":"error"}>{result.text}{result.ok&&<><br/><br/>Pesan: Halo 😊 Terima kasih sudah komentar {result.c.keyword}.<br/>📥 Download PDF: {result.p.url}</>}</div>}</section></div><section className="panel"><h2>Campaign aktif</h2>{campaigns.map(c=><div className="campaign"><b>{c.name}</b><span>Keyword: {c.keyword}</span><span>{c.platforms.join(" + ")}</span><em>{c.active?"ACTIVE":"OFF"}</em></div>)}</section></>}
 {tab==="Campaigns"&&<section className="panel"><h2>Campaign Manager</h2><p>Keyword dan pesan otomatis.</p>{campaigns.map(c=><div className="campaign"><b>{c.name}</b><span>{c.keyword}</span><span>{c.product}</span><button className="toggle" onClick={()=>setCampaigns(v=>v.map(x=>x.id===c.id?{...x,active:!x.active}:x))}>{c.active?"ON":"OFF"}</button></div>)}</section>}
 {tab==="Products"&&<section className="panel"><h2>Digital Product Library</h2><p>PDF yang dapat dibagikan melalui link.</p><div className="products">{products.map(p=><article><div className="cover">PDF</div><div><b>{p.name}</b><small>Keyword: {p.keyword}</small><small>{p.file}</small><a href={p.url}>Preview link ↗</a></div></article>)}</div></section>}
 {(tab==="Instagram"||tab==="Facebook")&&<section className="panel connection"><div className="icon">{tab==="Instagram"?"◎":"f"}</div><h2>{tab} Connection</h2><p>Hubungkan melalui API resmi Meta. Token tidak disimpan di browser.</p><div className="connectiongrid"><div>Connection<b>Not Connected</b></div><div>Webhook<b>Not Connected</b></div><div>Messaging<b>Requires Meta setup</b></div></div><button className="primary">Connect {tab}</button></section>}
 {tab==="Activity"&&<section className="panel"><h2>Activity</h2>{["Instagram · @user123 · MAU · Sent","Facebook · User ABC · LKPD · Sent","Instagram · @guru.id · INGGRIS · Sent"].map(x=><div className="activity">{x}</div>)}</section>}
 {tab==="Analytics"&&<section className="panel"><h2>Analytics</h2><div className="bars">{[45,70,55,82,65,92,72].map((h,i)=><i style={{height:h+"%"}}></i>)}</div></section>}
 {tab==="Settings"&&<section className="panel"><h2>Settings</h2><div className="setting">Platform Connections <b>Instagram + Facebook via Meta API</b></div><div className="setting">Webhook <b>/api/webhooks/meta</b></div><div className="setting">Security <b>Tokens remain server-side</b></div></section>}
 <footer>© 2026 Hamisah • All Rights Reserved</footer></section></main>}
